import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { NotificationComponent } from './layout/notification/notification.component';
import { WelcomeComponent } from './layout/welcome/welcome.component';
import { TestComponent } from './layout/test/test.component';
import { AuthService } from './services/auth.service';
import { DatamaniputationService } from './services/datamaniputation.service';
import { ScoreComponent } from './layout/score/score.component';
import { FormsModule } from '@angular/forms';
import { AutoGeneratedComponent } from './auto-generated/auto-generated.component';
import { TeslistService } from './teslist.service';
import { HttpClientModule } from '@angular/common/http';
import { FooterComponent } from './footer/footer.component';
import { ChangeColorDirective } from './change-color.directive';
import { SecondLetterCapitalPipe } from './second-letter-capital.pipe';
import { StorageService } from './services/storage.service';
@NgModule({
  declarations: [
    AppComponent,
    NotificationComponent,
    WelcomeComponent,
    TestComponent,
    ScoreComponent,
    AutoGeneratedComponent,
    FooterComponent,
    ChangeColorDirective,
    SecondLetterCapitalPipe
  ],
  imports: [
    BrowserModule,
    FormsModule,
    AppRoutingModule,
    HttpClientModule
  ],
  providers: [ StorageService],
  bootstrap: [AppComponent]
})
export class AppModule { }
