import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { NotificationComponent } from './layout/notification/notification.component';
import { WelcomeComponent } from './layout/welcome/welcome.component';
import { TestComponent } from './layout/test/test.component';
import { AuthService } from './services/auth.service';
import { DatamaniputationService } from './services/datamaniputation.service';
import { ScoreComponent } from './layout/score/score.component';
import { FormsModule } from '@angular/forms';
import { AutoGeneratedComponent } from './auto-generated/auto-generated.component';
import { HttpClientInMemoryWebApiModule } from 'angular-in-memory-web-api';
import { TeslistService } from './teslist.service';
import { HttpClientModule } from '@angular/common/http';
@NgModule({
  declarations: [
    AppComponent,
    NotificationComponent,
    WelcomeComponent,
    TestComponent,
    ScoreComponent,
    AutoGeneratedComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    AppRoutingModule,
    HttpClientModule,
    HttpClientInMemoryWebApiModule.forRoot(TeslistService, { delay: 500 })
  ],
  providers: [ ],
  bootstrap: [AppComponent]
})
export class AppModule { }
